### ISSUE TITLE
Bezeichnungen

### ISSUE THREAD

**Issue by aaroniker** [Sysix/dynao-CMS#15]
Slots:
Ich fände (Modul-) Positionen passender, also auch getPosition (gerade wenn man bald mehrere Module auf einen Slot/eine Position setzen kann)

Templates (die man pro Template anlegen/auswählen kann):
Hier fände ich Ansicht (engl. View) besser, da man sonst mit Templates durcheinander kommen kann

Module:
würde ich so lassen

Navigationspkt Struktur:
Diesen in Inhalt (engl Content) umbenennen, da man hier auch Module verwaltet

---

Sonst noch was ändern ? Deine Vorschläge? Community fragen?

**Comment by Sysix** [comment]
ModulPosition ist zu lange.. ich glaub da müssen wir nochmal darüber reden :)
Der Rest ist :+1:

**Comment by aaroniker** [comment]
einfach nur Position :D ohne Modul

**Comment by aaroniker** [comment]
also zb getPosition

**Comment by Sysix** [comment]
ja aber getPosition als klassename etc ist auch blöd oder :D "block" würde ich es beschreiben.. aber ist auch nicht so genau

**Comment by aaroniker** [comment]
ne, block passt nicht ganz, finde position perfekt, ist ja nichts anderes als ne position :p und wieso ist das als klassenname blöd ? getPosition ist ja die Methode wie getSlot

**Comment by Sysix** [comment]
Position::getPosition ist doch kacke :D?

**Comment by aaroniker** [comment]
dann halt nur get :D hast ne alternative ?

**Comment by Sysix** [comment]
Möchte hier wieder mal anfangen:
Position find ich kacke, weil es man dann verwirrt sein kann, weils "Position" 2 Bedeutungen besitzt
Wieso passt Block nicht :)? Magento, vBulletin und paar andere Benutzten es.

**Comment by aaroniker** [comment]
ok block geht fit :D

**Comment by aaroniker** [comment]
irgendwie find ich block schon wieder unschön, gerade im plural - hab ich jetzt mal im deutschen von blocks auf blöcke umbenannt :D da würde mir position, positionen vieell besser gefallen
