### ISSUE TITLE
strpos vs in_array

### ISSUE THREAD

**Issue by Sysix** [Sysix/dynao-CMS#2]
Hallo ich hba gerade ein Test gemacht wer schneller ist:

strpos vs in_array?

Mein Code:

``` php
$string  = '|1|2|3|6|';
$gesucht = 3;
$gesucht2 = 7;
$durchlauf = 1000000;

$start = microtime(true);
$array = explode('|', $string);
for($i=0; $i<$durchlauf; $i++) {    
    if(in_array($gesucht, $array)) { }
}
$time = microtime(true) - $start;
echo 'in_array gefunden Dauer: '.$time.' Sekunden<br />';

$start = microtime(true);
for($i=0; $i<$durchlauf; $i++) {    
    if(strpos($string, '|'.$gesucht.'|') !== false) { }
}
$time = microtime(true) - $start;
echo 'strpos gefunden Dauer: '.$time.' Sekunden<br />';


$start = microtime(true);
$array = explode('|', $string);
for($i=0; $i<$durchlauf; $i++) {    
    if(in_array($gesucht2, $array)) { } 
}
$time = microtime(true) - $start;
echo 'in_array nicht gefunden Dauer: '.$time.' Sekunden<br />';

$start = microtime(true);
for($i=0; $i<$durchlauf; $i++) {    
    if(strpos($string, '|'.$gesucht2.'|') !== false) { }
}
$time = microtime(true) - $start;
echo 'strpos nicht gefunden Dauer: '.$time.' Sekunden<br />';
```

explode hab ich extra im Zeiterfassung mit riengehauen, da das in unseren Code auch als Zeit aufgefasst werden muss ;)

Wieso der Test? 
https://github.com/callofsorrow/dynao-CMS/commit/4bd06702987309c9e8db46cff3c9596bbb8489a0#L1L26 hab ich in_array mit strpos ersetzt.. weil das Codesparender war.. aber nicht perfomance

Was machen wir nun?
strpos drinlassen und die "wertvolle" Zeit verlieren oder wieder umbauen :)?

**Comment by Sysix** [comment]
Ergebnis:
in_array gefunden Dauer: 0.93909406661987 Sekunden
strpos gefunden Dauer: 1.0846588611603 Sekunden
in_array nicht gefunden Dauer: 1.0853350162506 Sekunden
strpos nicht gefunden Dauer: 1.0986318588257 Sekunden

Kannst ja mal auf dein Server testen was schneller ist :)

**Comment by aaroniker** [comment]
bin für in_array

nacher müssen wir eh nochmal alles auf Ladezeit usw optimieren ;)

**Comment by Sysix** [comment]
wär ich eig auch dafür :) teste aber mal bei dir: und mal mit der String Variable:

$string  = '|1|2|3|6|8|11|15|18|';

Mein Ergebnis

in_array gefunden Dauer: 0.95810699462891 Sekunden
strpos gefunden Dauer: 1.1154890060425 Sekunden
in_array nicht gefunden Dauer: 1.5802140235901 Sekunden
strpos nicht gefunden Dauer: 1.1833531856537 Sekunden

Array gewinnt nur wenn er es gefunden hat ;) wenn das Feld nicht gibt, ist strpos schneller :/

**Comment by aaroniker** [comment]
$string  = '|1|2|3|6|';

in_array gefunden Dauer: 0.38554811477661 Sekunden
strpos gefunden Dauer: 0.44725894927979 Sekunden
in_array nicht gefunden Dauer: 0.44385719299316 Sekunden
strpos nicht gefunden Dauer: 0.47183299064636 Sekunden

$string = '|1|2|3|6|8|11|15|18|';

in_array gefunden Dauer: 0.38798904418945 Sekunden
strpos gefunden Dauer: 0.44508910179138 Sekunden
in_array nicht gefunden Dauer: 0.65973806381226 Sekunden
strpos nicht gefunden Dauer: 0.51500916481018 Sekunden

**Comment by Sysix** [comment]
``` php
$string  = '|1|2|3|6|8|11|15|18|';
$gesucht = 3;
$gesucht2 = 7;
$durchlauf = 500000;

$start = microtime(true);
$array = explode('|', $string);
for($i=0; $i<$durchlauf; $i++) {    
    if(in_array($gesucht, $array)) { }
}
$time = microtime(true) - $start;
echo 'in_array gefunden Dauer: '.$time.' Sekunden<br />';

$start = microtime(true);
for($i=0; $i<$durchlauf; $i++) {    
    if(strpos($string, '|'.$gesucht.'|') !== false) { }
}
$time = microtime(true) - $start;
echo 'strpos gefunden Dauer: '.$time.' Sekunden<br />';

$start = microtime(true);
$array = explode('|', $string);
$array = array_flip($array);
for($i=0; $i<$durchlauf; $i++) {    
    if(isset($array[$gesucht])) { }
}
$time = microtime(true) - $start;
echo 'isset(arraykey) gefunden Dauer: '.$time.' Sekunden<br />';



$start = microtime(true);
$array = explode('|', $string);
for($i=0; $i<$durchlauf; $i++) {    
    if(in_array($gesucht2, $array)) { } 
}
$time = microtime(true) - $start;
echo 'in_array nicht gefunden Dauer: '.$time.' Sekunden<br />';

$start = microtime(true);
for($i=0; $i<$durchlauf; $i++) {    
    if(strpos($string, '|'.$gesucht2.'|') !== false) { }
}
$time = microtime(true) - $start;
echo 'strpos nicht gefunden Dauer: '.$time.' Sekunden<br />';


$start = microtime(true);
$array = explode('|', $string);
$array = array_flip($array);
for($i=0; $i<$durchlauf; $i++) {    
    if(isset($array[$gesucht2])) { }
}
$time = microtime(true) - $start;
echo 'isset(arraykey) nicht gefunden Dauer: '.$time.' Sekunden<br />';

```

in_array gefunden Dauer: 0.48958706855774 Sekunden
strpos gefunden Dauer: 0.56606411933899 Sekunden
isset(arraykey) gefunden Dauer: 0.10742783546448 Sekunden
in_array nicht gefunden Dauer: 0.78684520721436 Sekunden
strpos nicht gefunden Dauer: 0.59721112251282 Sekunden
isset(arraykey) nicht gefunden Dauer: 0.095603942871094 Sekunden

ich glaub die 3te Methode mit array_flip gewinnt jetzt !! :)

Nette Seite: http://ryanday.org/index_php.php

**Comment by aaroniker** [comment]
hui :D jo, sieht um einiges performanter aus :)
