### ISSUE TITLE
Icon font? oder svg?

### ISSUE THREAD

**Issue by aaroniker** [Sysix/dynao-CMS#23]
Wollen wir weiterhin FontAwesome nutzen oder evtl auf svg icons umstellen?

Vorteile wären:
- schnellere Ladezeiten, es werden nur die geladen, die gebraucht werden
- schärfer / schöner (!)
- mehr Optionen über CSS 3

Nachteile
- IE 8 packt das nicht (bezweifle das der noch wichtig für uns ist)

**Comment by Sysix** [comment]
ich würde das FontAweSome pack lassen :)
das nicht alle icons verbaut sind, bedeutet nicht, dass sie nicht gebraucht werden :)
So haben Addon Entwickler schon automatisch eine Bibliothek an Icons und können diese ganz leicht auch benutzten :)

Und die Fonts kann man auch wunderbar mit CSS3 Stylen :)
