### ISSUE TITLE
autoload function für Klassen

### ISSUE THREAD

**Issue by Sysix** [Sysix/dynao-CMS#4]
Wir müssen uns Überlegen wie mir die autoload class für die anderen Klassen machen, da es bei uns paar Probleme gibt:

Standard:
Die Klasse hat genau den gleichen Namen wie der Dateinamen

Falls wir jede Datei im ordner classes includen kann es zu einen Fehler kommen, da es Kindklassen gibt.

Deswegen meien Überlegungen jede Datei erstmal öffnen schauen obs ne Kindklasse ist, wenn ja => In Warteschleife stecken und warten bis die Vaterklasse included wird.

Dann die Kindklasse includen
Dafür hab ich mal nen kleinen Script programmiert:

Öffnet die Klasse Datei mit den ersten 200 Ziffern
mit regex schauen ob Kindklasse ist oder nicht

``` php
$section = file_get_contents('admin/lib/classes/form/text.php', NULL, NULL, 0, 200);
echo htmlspecialchars($section).'<br />';
$section = preg_match('/class (\w+) extends (\w+)/', $section, $treffer);
```

```
/ #Anfang
class # Muss mit class  beginnen
 (\w+) #Alle Möglichen buchstaben, Zahlen und Zeichen
 extends  #Muss dann extends besitzen
(\w+)  #Alle Möglichen buchstaben, Zahlen und Zeichen
/ Ende
```

Als Result würde dann das kommen

``` php
Array (
    [0] => class formText extends formField
    [1] => formText
    [2] => formField
)
```

**Comment by Sysix** [comment]
so würde die Funktion aussehen. Cache müsste dann später noch gemacht werden :)

``` php
// Globale Variablen
$mainClasses = array();
$subClasses = array();

function selectClasses($dir) {

    // Globale Variablen einbezihene
    global $mainClasses;
    global $subClasses;

    // Ordner öffnen und Dateien in $files speichern
    $files = scandir($dir);

    // Jede Datei durchforten
    foreach($files as $file) {

        // Unzulässige Dateien
        if(in_array($file, array('.', '..'))) {
            continue;   
        }

        // Ist Ordner? Wenn ja dann Function erneut aufrufen
        if(strpos($file, '.php') === false) {
            selectClasses($dir.'/'.$file);
            continue;
        }       

        // Datei einlesen und die ersten 200 Zeichen schauen ob es eine Kindklasse ist oder nicht
        $section = file_get_contents($dir.'/'.$file, NULL, NULL, 0, 200);
        $section = preg_match('/class (\w+) extends (\w+)/', $section, $treffer);
        if(isset($treffer[1])) { # Ist Kindklasse
            $subClasses[] = $dir.'/'.$file; 
        } else { # Ist Vaterklasse
            $mainClasses[] = $dir.'/'.$file;    
        }

    }

}

// Funktion öffnen
selectClasses('admin/lib/classes');

// Hauptklasse einbinden
foreach($mainClasses as $class) {
    require_once($class);
}


// Kindklassen einbinden
foreach($subClasses as $class) {
    require_once($class);
}
```

**Comment by aaroniker** [comment]
ist doch ne gute Lösung, sonst vllt über den Dateinamen ? nen Unterordner ?

**Comment by Sysix** [comment]
wiem einste genau über dateinamen? Unterordner werden automatisch miteinbezogen :) siehe `if(strpos($file, '.php') === false) {`

**Comment by Sysix** [comment]
finde aber die Methode trotzdem kacke :/
wir müssen eine Einheit reinbringen :)
immoment shcaut so aus:
form.php = class form
form/text.php = class formText
form/button.php 0 class formButton
(form/text/readonly.php) = class formTextReadonly

da kann man ne struktur reinbringen ;)
http://www.phpliveregex.com/

**Comment by aaroniker** [comment]
wieso ? funktioniert doch oder ? zu langsam ?

**Comment by aaroniker** [comment]
sonst können wir doch eigl die autoload Funktion von php5 nutzen - siehe hier : 

http://www.peterkropff.de/site/php/autoload.htm

hier scheint es auch zu gehen, dann ne Exception für 5.3 schreiben und gut, oder check ich da was nicht ? :D

**Comment by Sysix** [comment]
bei deinen Beispiel ist der Klassenname = die Dateiname.
aber z.B. haben wir formText classe.. aber die datei heißt nur text ist aber dafür im form ordner

**Comment by aaroniker** [comment]
achso ... :/ hm, sonst ka :D was stimmt denn mit der aktuellen funktion nicht ?

**Comment by aaroniker** [comment]
sonst wär die autoload funktion von php5 direkt ja ganz nice, da klassen erst geladen werden, wenn diese benötigt werden

**Comment by Sysix** [comment]
die aktuelle Version gefällt mir net.. jede Datei öffnen? das muss! doch leider gehen :)
Und eine Struktur brauchen wir auch :) also wieso net so wie ich gesagt hab :)?

**Comment by aaroniker** [comment]
also anhand vom Pfad den klassennamen herausfinden ?

**Comment by Sysix** [comment]
Ja hal den Namen kurz schreiben wie text.php und im Ordner form dann ergibt sich automatisch der klassenname formText.php

**Comment by Sysix** [comment]
Class formText i mean

**Comment by aaroniker** [comment]
oder dann auch mit ner Funktion ? Was ist dann daran besser als bei der aktuellen ?

**Comment by Sysix** [comment]
- Code kleiner
- Code Schneller, Chach muss ja trotzdem erstellt werden :D
- Code Übersichtlicher
- Eine Einheit reingebracht

**Comment by Sysix** [comment]
glubschte: https://github.com/callofsorrow/dynao-CMS/commit/6745ae43871eed5df8469c91097290061dd5580d
