### ISSUE TITLE
PDO nutzen ?

### ISSUE THREAD

**Issue by aaroniker** [Sysix/dynao-CMS#5]
Bin auf folgendes gestoßen :

http://cmstutorials.org/tutorial/view/why_you_should_be_using_phps_pdo_for_database_access

So können wir verschiedene Datenbanken unterstützen .. was hälts davon ?

**Comment by Sysix** [comment]
Ich würde weiterhin MYSQLI benutzten, da die Datenbank-Auswahl bei uns sowieso nur sql bleibt :) die anderen Vorteile kann man in unseren sql-klasse automatisch einbinden.
Zudem ist Mysqli ein stückchen schneller :D

**Comment by aaroniker** [comment]
alles klar ;)
