### ISSUE TITLE
Namen für einzelne Sachen?

### ISSUE THREAD

**Issue by Sysix** [Sysix/dynao-CMS#7]
Hey hey,

wir sollten uns langsam überlegen einen Namen für unsere einzelnen Seiten zu nehmen.
Sprich wie heißt bei uns z.B: eine Seite, oder ein Bereich einer Seite.
Structure wär ja sinnlos weil es ja ein Artikel ist und keine Struktur.

Mein Vorschlag:

Komplette Seite: article
Bereich der Seite (von Modul zusammengesetzt): article_area

Mir ist das Wichtig, da die Artikelbereiche noch in der module Klasse sind, obwohl es ein andere Arbeitschritt (= andere Klasse) sein sollte.

**Comment by aaroniker** [comment]
Artikel ist unpassend find ich : http://de.wikipedia.org/wiki/Artikel

wieso nicht einfach page ? und nen bereich zb pagebox? 

bzw welche Namen meinst du konkret ? also wo tauchen die auf ?

**Comment by Sysix** [comment]
page könnten wir nehmen, aber pagebox? 
find ich unpassender :D

Die Namen tauchen in den Klassen auf, die später miteinander Verbunden werden. Immoment ist für "pagebox/article_area" die Einstellungen in der module Klasse.

Und wieso passt Artikel nicht? _lat. articulus „Abschnitt“,_ Ist das kein Abschnitt der Internetseite :)?

**Comment by aaroniker** [comment]
na irgendwie find ich nen Artikel wird allgemein mehr als jounalistischer Text, oder Teil eines Kapitels verstanden -  also eigl nur Textform :D

also dann für Seiten einfach "page" oder "site" - da weiß man, was gemeint ist
für die Bereiche wären meine Vorschläge : box, field, area

**Comment by Sysix** [comment]
also dann:
- page
- pageArea
- module

die 3 Klassen?
ich finde page kann man aber auch als Unterseite vom Backend sehen. weil wir ja mit $_GET['page'] arbeitn :)

**Comment by aaroniker** [comment]
ist ja nicht schlimm - besser als wenn wir jetzt site oder so noch mit reinnehmen
