### ISSUE TITLE
Skype Besprechungen

### ISSUE THREAD

**Issue by Sysix** [Sysix/dynao-CMS#8]
Hallo,

wirh aben schon seit Monaten nichtmehr miteinander diskutiert (auch andere Mitglieder hier bei uns). Ich bitte euch einen geregelten Ablauf einzuplanen. Damit ihr **mindestens** eine Halbe Stunde in der Woche Zeit habt für das CMS. 

Die Halbe Stunde wird folgendes besprochen:
- Aktueller Stand
- Bugs
- Community (Forum) einbinden
- Wünsche etc.

Da ich persönlich immer erst ab 6Uhr daheim bin. Ergibt es einen Zeitraum von 18:00 Uhr bis 22 Uhr.

Natürlich muss ich jetzt selbst nicht immer dabei sein :warning: .
Falls was Wichtiges besprochen worden ist, bitte hier irgendwie Vermerken, damit die anderne, die nicht dabei waren natürlich auch UptoDate sind.

Gruß Sysix

**Comment by aaroniker** [comment]
so nämlich! :D
